import { unicodeDateTimeTokenDefinitions } from './unicode-datetime-token-definitions';

export const datetimeTokenResolveOrder: Partial<Record<keyof typeof unicodeDateTimeTokenDefinitions, number>> = {
  'eraShort': 1,
  'eraLong': 1,
  'eraNarrow': 1,
  'commonEraShort': 1,
  'commonEraLong': 1,
  'commonEraNarrow': 1,
  'calendarYear': 1,
  'isoYear': 1,
  'signedIsoYear': 1,
  'negativeSignedIsoYear': 1,
  'month': 2,
  'monthPadded': 2,
  'monthShort': 2,
  'monthLong': 2,
  'monthNarrow': 2,
  'monthStandaloneShort': 2,
  'monthStandaloneLong': 2,
  'monthStandaloneNarrow': 2,
  'day': 3,
  'dayPadded': 3,
  'weekdayShort': 4,
  'weekdayLong': 4,
  'weekdayNarrow': 4,
  'weekdayStandaloneShort': 4,
  'weekdayStandaloneLong': 4,
  'weekdayStandaloneNarrow': 4,
  'weekdayLocal': 4,
  'weekdayLocalPadded': 4,
  'weekday': 5,
  'weekdayPadded': 5,

  'dayPeriod': 6,
  'dayPeriodShort': 6,
  'dayPeriodLong': 6,
  'dayPeriodNarrow': 6,
  'twelveHour': 7,
  'twelveHourPadded': 7,
  'hour': 8,
  'hourPadded': 8,
  'minute': 9,
  'minutePadded': 9,
  'second': 10,
  'secondPadded': 10,
  'nanosecond': 11,
  'timeZoneNameShort': 12,
  'timeZoneNameLong': 12,
  'timeZoneNameShortGeneric': 12,
  'timeZoneNameLongGeneric': 12,
}
